# Generated by Django 3.2.9 on 2021-11-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_names',
            new_name='category_name',
        ),
    ]
