# Generated by Django 3.2.9 on 2021-11-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_category_names_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slut',
            new_name='slug',
        ),
    ]
